PUT http://localhost:3003/api/blogs/60ad01907e22e71de1e67c50
Content-Type: application/json

{
"title": "Tokens and programming II",
"author": "Token",
"url": "http://www.tokensII.com"
}

//likes 0 by default